version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "internship_nodejs"
      MYSQL_USER: "huytiep"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./data/mysql/:/docker-entrypoint-initdb.d/
  mongodb:
      image: mongo
      container_name: mongo
      ports:
        - "27000:27017"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intership
    working_dir: /usr/nodejs_intership
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - mongodb